services:
  blazorwebassemblydocker:
    image: blazorwebassembly.Server
    build:
      context: .
      dockerfile: Server/Dockerfile
    ports:
      - "8080:80"  # Map host port 8080 to container port 80
      - "8443:443" # Map host port 8443 to container port 443
